# Generated by Django 2.1.1 on 2019-07-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_id', models.CharField(max_length=5, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=50)),
                ('main_text', models.CharField(max_length=2000)),
                ('split_text1', models.CharField(blank=True, max_length=300)),
                ('split_text2', models.CharField(blank=True, max_length=300)),
                ('split_text3', models.CharField(blank=True, max_length=300)),
                ('split_text4', models.CharField(blank=True, max_length=300)),
                ('split_text5', models.CharField(blank=True, max_length=300)),
                ('split_text6', models.CharField(blank=True, max_length=300)),
                ('split_text7', models.CharField(blank=True, max_length=300)),
                ('split_text8', models.CharField(blank=True, max_length=300)),
                ('split_text9', models.CharField(blank=True, max_length=300)),
                ('split_text10', models.CharField(blank=True, max_length=300)),
                ('split_text11', models.CharField(blank=True, max_length=300)),
                ('update_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
